name: vertx-core (5.x)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 11
            stable: true
          - os: ubuntu-latest
            jdk: 11
            profile: '-PNativeEpoll'
            stable: true
          - os: ubuntu-latest
            jdk: 11
            profile: '-PNativeIoUring --fail-never'
            stable: false
          - os: ubuntu-latest
            jdk: 11
            profile: '-PNativeEpoll+DomainSockets'
            stable: true
          - os: ubuntu-latest
            jdk: 21
            stable: true
          - os: windows-latest
            jdk: 11
            stable: true
#          - os: macos-latest
#            jdk: 11
#            profile: '-PNativeKQueue'
#            stable: false
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      profile: ${{ matrix.profile }}
      stable: ${{ matrix.stable }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'eclipse-vertx' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: CI
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.pull_request.head.sha || github.ref_name }}
      jdk: 11
    secrets: inherit
